# Generated by Django 5.0.3 on 2024-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_roomtype_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='way_of_staying',
            field=models.CharField(choices=[('AIR', 'Аэропорт'), ('TRAIN', 'ЖД-пути'), ('OWN', 'Своим ходом')], default='OWN', max_length=30),
        ),
    ]
