# Generated by Django 5.0.3 on 2024-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_booking_way_of_staying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='country',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='country',
            field=models.CharField(default='Казахстан', max_length=255),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1),
        ),
    ]
