# Generated by Django 5.0.3 on 2024-04-24 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_guestprofile_guest_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 20, 9, 0, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
