# Generated by Django 5.0.3 on 2024-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_guestprofile_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
